name: Main

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 10 * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: tanq16
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - run: chmod +x ./security_docker_main/local-builder-script.sh
      - run: cd ./security_docker_main && bash local-builder-script.sh
