version: 2.1
jobs:
  cst-rice-arm64:
    machine:
      image: ubuntu-2204:current
      # docker_layer_caching: true
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: Docker Login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Execute Build Script
          command: |
            cd security_docker
            docker build -f builder.Dockerfile -t intermediate_builder .
            docker builder prune -f
            docker build -t tanq16/sec_docker:main_apple .
            docker push tanq16/sec_docker:main_apple

workflows:
  build-arm-images:
    when: pipeline.git.branch == "main"
    jobs:
      - cst-rice-arm64
