name: CST General

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: amd64
            runs_on: ubuntu-latest
            tag: amd
          - arch: arm64
            runs_on: ubuntu-24.04-arm
            tag: arm
    runs-on: ${{ matrix.runs_on }}
    env:
      DOCKER_BUILDKIT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: tanq16
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Image
        run: |
          cd images/general
          docker build -f builder.Dockerfile -t intermediate_builder .
          docker builder prune -f
          docker build -f Dockerfile -t tanq16/cst-general:${{ matrix.tag }} .
          docker push tanq16/cst-general:${{ matrix.tag }}
