name: Minimal

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 1,11,22 * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'run'
        required: false 
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: tanq16
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        
      - name: Build and push security docker
        uses: docker/build-push-action@v2
        with:
          context: security_minimal_docker
          push: true
          tags: tanq16/sec_docker:minimal
