name: CST Rice Build & Push

on:
  push:
    branches:
      - 'main'
  # schedule:
  #   - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  amd64:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: tanq16
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - run: |
          cd security_docker
          docker build -f builder.Dockerfile -t intermediate_builder .
          docker builder prune -f
          docker build -f Dockerfile -t tanq16/sec_docker:main .
          docker push tanq16/sec_docker:main

  # arm64:
  #   runs-on: ubuntu-latest
  #   env:
  #     DOCKER_BUILDKIT: '1'
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v3
  #       with:
  #         username: tanq16
  #         password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  #     - run: |
  #         cd security_docker
  #         docker buildx build -o type=docker --platform=linux/arm64 -f builder.Dockerfile -t intermediate_builder .
  #         docker builder prune -f
  #         docker buildx build -o type=docker --platform=linux/arm64 -f Dockerfile -t tanq16/sec_docker:main_apple .
  #         docker push tanq16/sec_docker:main_apple
